graph TD
Title: ERC20/223トークン支払いの処理
start(支払い要求)
start --> 要求チェック{妥当な支払い要求要求?}
要求チェック -->|No| revert["revert()"]
要求チェック -->|Yes| 支払い済みチェック{"既に支払済か？"}

支払い済みチェック -->|No| revert
支払い済みチェック -->|Yes| 換算[支払うトークンを計算]

換算 --> 送金[トークンをユーザーへ送金する]
送金 --> 送金成否{"送金できたか？"}

送金成否 -->|失敗| revert
送金成否 -->|成功| 支払記録[支払い済みの記録]

支払記録 --> 記録成否{成否}

記録成否 -->|失敗| revert
記録成否 -->|成功| finish[処理完了]

