graph TD
start(Request transfer of token) --> InternalDdistributionTokens["Is the signature used in internal distribution tokens?"]

InternalDdistributionTokens -->|No| revert["revert()"]
InternalDdistributionTokens -->|Yes| SelfCheck["Is the information derived from the signature and parameters valid?"]

SelfCheck -->|No| revert["revert()"]
SelfCheck -->|Yes| History["Already transferred?"]

History -->|Yes| revert
History -->|No| Calculation["Calculate the number of ERC tokens"]

Calculation --> ERCToken[Transfer a token]
ERCToken --> TransferSucceed["Did transfer succeed?"]

TransferSucceed -->|No| revert
TransferSucceed -->|Yes| Record["Record as transferred"]

Record --> Successful["Successful?"]

Successful -->|No| revert
Successful -->|Yes| finish["complete"]

